version: "3.8"

services:
  gofiber_app:
    build: .
    container_name: agriboost-backend
    ports:
      - ":"
    networks:
      -  
    env_file:
      - .env
    restart: unless-stopped

networks:
  existing_network:
    external: true 
