version: "3.8"

services:
  gofiber_app:
    build: .
    container_name: agriboost-backend
    ports:
      - ":"
    networks:
      -  network_name
    env_file:
      - .env
    restart: unless-stopped

networks:
  network_name:
    external: true 
