services:
  postgres-intern-bcc:  
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: intern_bcc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  agriboost:
    build: .
    ports:
      - "8083:8083"

volumes:
  pgdata:
